# Generated by Django 4.2 on 2023-04-18 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(max_length=30)),
                ('data_cadastro', models.DateField(default=datetime.date.today)),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(blank=True, max_length=30, null=True)),
                ('data_emprestado', models.DateTimeField(blank=True, null=True)),
                ('data_devolocao', models.DateTimeField(blank=True, null=True)),
                ('tempo_duracao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
