# Generated by Django 4.2 on 2023-04-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='co_autor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
